mysql: easymail:easymail@tcp(192.168.1.168:3306)/easymail?charset=utf8&parseTime=True&loc=Local
redis: 192.168.1.168:6379
log_file: easymail.log
init_db: true
lmtp:
  storage:
    root: ./storage
    data: ./data
apps:
  - name: dovecot
    family: tcp
    listen: 0.0.0.0:10025
    enable: true

  - name: policy
    family: tcp
    listen: 0.0.0.0:10026
    enable: true

  - name: filter
    family: tcp
    listen: 0.0.0.0:10027
    enable: true

  - name: lmtp
    family: tcp
    listen: 0.0.0.0:10028
    enable: true

